default: &default
  host: db
  user: root
  password: password
  adapter: mysql
  port: '3306'
  skip_dumping_schema_sql: true # https://imdrasil.github.io/jennifer.cr/docs/configuration, chave necessária para criação das migrations

development:
  <<: *default
  db: app_db

test:
  <<: *default
  db: app_db

production:
  <<: *default
  db: app_db
