default: &default
  host: localhost
  user: user_name
  password: password
  adapter: mysql

development:
  <<: *default
  db: application_database_name_development

test:
  <<: *default
  db: application_database_name_test

production:
  <<: *default
  db: application_database_name_production
