# === Sam shortcut
# The following lines are autogenerated and any changes will be
# discarded if Sam regenerates this file.
CRYSTAL_BIN = crystal
CRYSTAL_PATH := $(if $(shell command -v $(CRYSTAL_BIN) 2>/dev/null),$(shell command -v $(CRYSTAL_BIN) 2>/dev/null),$(error '`$(CRYSTAL_BIN)` not found, please install it and/or ensure it is in your PATH'))
SAM_PATH ?= "sam.cr"
.PHONY: sam
sam:
	$(CRYSTAL_PATH) $(SAM_PATH) $(filter-out $@,$(MAKECMDGOALS))
%:
	@:
# === Sam shortcut
